"""
=============================================================================
Cytosine Deaminase Sequence Context Preference Analysis
=============================================================================
Purpose:
    Analyzes a BAM file generated by Bismark alignment (used here purely as
    a C->T mismatch-tolerant aligner, NOT for bisulfite sequencing) to
    determine the sequence context preference of a cytosine deaminase
    enzyme.

Biological model:
    - Your enzyme deaminates cytosine (C) to uracil (U), which is read as
      thymine (T) during sequencing.
    - Every C->T mismatch in a read relative to the reference is treated as
      a deamination event.
    - There is NO bisulfite chemistry in this experiment. Bismark is used
      only because it aligns reads containing C->T changes without
      penalising them as mismatches.

Notes:
      Every reference C (or G on the minus strand) covered at
      >= MIN_COVERAGE reads is kept, and every C->T (or G->A) read at that
      site is counted as a deamination event — no thresholding, no
      "called" vs. "background" distinction.
    - The script reports the reference genome's own
      base composition (genome-wide, and position-by-position across the
      +/-3 flanking window) in a standalone workbook, so you can apply any
      normalization you want by hand.
    - The sequence logo and position-frequency heatmap (plots 9 and 10) are weighted by
      the number of deamination observations at each site (n_deaminated. A site with 11 of 40 reads
      showing C->T contributes 11 counts to the logo; a site with 1 of 23
      contributes 1 count. Heights are plain observed frequencies.
    - A plot/table reports % C->T conversion broken out by the +1
      sequence context (CpG / CpA / CpC / CpT): for each dinucleotide
      class, all covered-site read coverage in that class is the
      denominator and all C->T observations in that class are the
      numerator.
    - (optional): plots 09b/10b. Plots 09/10 use raw observed
      frequencies with no genome-composition correction. Setting
      GENERATE_COMPOSITION_CORRECTED = True in Cell 1's CONFIG additionally
      produces 09b/10b: the same heatmap and logo, but with each flanking
      position's base frequencies divided by that position's own genomic
      background frequency (from the reference genome's C-window
      composition) and renormalized to sum to 1 -- i.e. "as if every base
      were equally represented in the genome at that position." This adds
      two extra plots/workbooks alongside 09/10; it does not replace them.

How to use this script in Spyder (organized into 3 cells, run in order):

    CELL 1 (always run first): imports, config, and helper function
    definitions. No heavy computation happens here.

    CELL 2 (slow — scans the BAM and the reference genome once):
    Collects per-site C->T counts from the treated BAM and scans the
    reference FASTA for genome-wide and position-wise base composition.
    Re-run this only if you change the BAM/FASTA paths or the read-
    filtering config in Cell 1.

    CELL 3 (fast — re-run freely once Cell 2 has been run):
    Computes the deamination-weighted position frequencies and +1-context
    conversion rates, generates plots 09/10/11, and writes all Excel/CSV
    outputs.

Pipeline context:
    Input BAM file processed through:
      - Bismark genome preparation (C->T and G->A converted genomes)
      - TrimGalore! trimming
      - Bismark Bowtie2 alignment
      - Picard sorting + MarkDuplicates deduplication

Requirements:
    pip install bamnostic pyfaidx numpy pandas matplotlib openpyxl

=============================================================================
"""

# %% CELL 1 — Imports, configuration, and helper functions
# Run this cell first. It does not perform any heavy computation.

# -- Standard library ---------------------------------------------------------
import os
import sys
import warnings
from collections import Counter, defaultdict

# -- Third-party ---------------------------------------------------------------
try:
    import bamnostic as bs
except ImportError:
    sys.exit("ERROR: bamnostic not found.\n"
             "Install with:  python.exe -m pip install bamnostic")

try:
    import pyfaidx
except ImportError:
    sys.exit("ERROR: pyfaidx not found.\n"
             "Install with:  python.exe -m pip install pyfaidx")

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import TwoSlopeNorm
from matplotlib.textpath import TextPath
from matplotlib.patches import PathPatch
from matplotlib.transforms import Affine2D
from matplotlib.font_manager import FontProperties
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from openpyxl.formatting.rule import ColorScaleRule

warnings.filterwarnings("ignore", category=UserWarning)

matplotlib.rcParams.update({
    "figure.facecolor" : "white",
    "axes.facecolor"   : "white",
    "axes.spines.top"  : False,
    "axes.spines.right": False,
    "font.family"      : "Arial",
    # If Arial isn't installed on this machine, matplotlib silently falls
    # back to its default sans-serif font (DejaVu Sans) instead of erroring
    # -- this is expected on Windows, where Arial ships by default.
    # Embed text as real (TrueType) font outlines rather than Type 3 bitmap
    # fonts in PDF output, so text stays selectable/editable text in Adobe
    # Illustrator rather than importing as an image of each glyph.
    "pdf.fonttype"     : 42,
    "ps.fonttype"      : 42,
})


# =============================================================================
# ██████████████████████████   C O N F I G   ██████████████████████████████
# =============================================================================

# -- Required paths -----------------------------------------------------------

BAM_FILE   = r"path/to/your_sample.sorted.dedup.bam"
REF_FASTA  = r"path/to/reference_genome.fa"
OUTPUT_DIR = r"path/to/output_folder"

# -- Context window -------------------------------------------------------------
# FLANK_SIZE = 3 gives a 7-mer: [-3][-2][-1][C][+1][+2][+3]
FLANK_SIZE = 3

# -- Read filtering ---------------------------------------------------------------
MIN_BASE_QUALITY = 20   # Phred score at the cytosine (or guanine, minus strand) position
MIN_MAPPING_QUAL = 20   # Read MAPQ score

# Minimum coverage to keep a site at all. Every C->T (or G->A) observation
# at a kept site is treated as a real deamination event -- there is no
# rate threshold and no control comparison, so this floor exists only to
# drop essentially-uncovered/unreliable sites.
MIN_COVERAGE = 8

# -- Chromosomes to analyse -----------------------------------------------------
# [] = all chromosomes. Restrict to a subset for faster testing,
# e.g. CHROMOSOMES = ["lambda"] or CHROMOSOMES = ["chr1"]
CHROMOSOMES = []

# -- Optional composition-corrected plots (09b/10b) ------------------------------
# The main plots 09/10 use raw observed frequencies (no genome-composition
# correction -- see the reference genome base composition workbook). Setting
# this to True additionally generates 09b/10b: the same heatmap and logo,
# but with each position's base frequencies divided by that position's own
# genomic background frequency (from the reference genome's C-window
# composition) and renormalized back to sum to 1 -- i.e. "as if every base
# were equally represented in the genome at that position." This does NOT
# change or replace 09/10; it adds two extra plots/workbooks alongside them.
GENERATE_COMPOSITION_CORRECTED = True

# =============================================================================
# END OF CONFIG
# =============================================================================


# ── Constants ─────────────────────────────────────────────────────────────
COMPLEMENT  = str.maketrans("ACGTacgt", "TGCAtgca")
BASES       = ["A", "C", "G", "T"]
BASE_COLORS = {"A": "#2ecc71", "C": "#3498db", "G": "#f39c12", "T": "#e74c3c"}

# Standard Sanger/ABI trace color convention (A-green, C-blue, G-black,
# T-red), used by the letter-glyph sequence logo (plot 10).
SANGER_BASE_COLORS = {"A": "#109648", "C": "#255C99", "G": "#000000", "T": "#D62B2B"}
# Fixed vertical stacking order for plot 10, bottom-to-top. Listing T first
# means it's drawn first (at the bottom of the stack); A last means it ends
# up on top. This is a FIXED order (always A/C/G/T top-to-bottom,
# alphabetical) rather than sorted by frequency.
LOGO_STACK_ORDER_BOTTOM_TO_TOP = ["T", "G", "C", "A"]

# +1 dinucleotide context classes, in the order requested for plot 11.
DINUC_CONTEXTS = ["CpG", "CpA", "CpC", "CpT"]
DINUC_BASE_OF  = {"CpG": "G", "CpA": "A", "CpC": "C", "CpT": "T"}


# ── Helper functions ─────────────────────────────────────────────────────

def reverse_complement(seq: str) -> str:
    return seq.translate(COMPLEMENT)[::-1]


def make_output_dir(path: str):
    os.makedirs(path, exist_ok=True)
    print(f"Output directory: {os.path.abspath(path)}")


def get_chromosomes_from_header(bam, user_chroms: list) -> list:
    header = bam.header
    try:
        sq_list   = header.get("SQ", [])
        available = [entry["SN"] for entry in sq_list]
    except Exception:
        available = list(header.get("SQ_names", []))

    if not available:
        print("  WARNING: Could not read chromosome names from BAM header.")
        return user_chroms if user_chroms else []

    print(f"  Reference sequences in BAM: {available}")

    if user_chroms:
        missing = [c for c in user_chroms if c not in available]
        if missing:
            print(f"  WARNING: chromosomes not found in BAM, skipping: {missing}")
        return [c for c in user_chroms if c in available]
    return available


def fetch_context(fasta: pyfaidx.Fasta, chrom: str,
                  pos: int, flank: int) -> str:
    """Return the 2*flank+1 reference sequence centred on pos (0-based)."""
    chrom_len = len(fasta[chrom])
    start, end = pos - flank, pos + flank + 1
    if start < 0 or end > chrom_len:
        return None
    ctx = str(fasta[chrom][start:end]).upper()
    return None if "N" in ctx else ctx


def parse_cigar(read) -> list:
    """
    Walk the CIGAR string and return (query_index, ref_position) pairs
    for every aligned (non-gap) base.
    CIGAR ops: 0=M, 1=I, 2=D, 3=N, 4=S, 5=H
    """
    pairs     = []
    query_pos = 0
    ref_pos   = read.reference_start

    for op, length in read.cigar:
        if op == 0:
            for i in range(length):
                pairs.append((query_pos + i, ref_pos + i))
            query_pos += length
            ref_pos   += length
        elif op == 1:
            query_pos += length
        elif op == 2:
            ref_pos += length
        elif op == 3:
            ref_pos += length
        elif op == 4:
            query_pos += length
        # op == 5 (H): consumes neither

    return pairs


def collect_sites(bam_path: str,
                  ref_path: str,
                  chromosomes: list,
                  flank_size: int,
                  min_bq: int,
                  min_mq: int,
                  min_cov: int) -> pd.DataFrame:
    """
    Iterate over all reads in the BAM. At every reference C (or G for
    minus strand), record how many reads show C/T (or G/A). Aggregate
    into per-site deamination counts with sequence context.

    Every C->T (or G->A) read at a kept site is counted as a deamination
    event directly.

    Only reads that genuinely derive from the strand carrying the cytosine
    in question are counted (gated on BAM FLAG 0x10, i.e. the read's own
    alignment strand): a read from the opposite strand covering the same
    coordinate has no C there at all and can never show a converted base,
    so including it would only inflate coverage without ever contributing
    to the deaminated count.
    """
    print("\n" + "="*60)
    print("Collecting per-site deamination counts")
    print("="*60)

    fasta = pyfaidx.Fasta(ref_path)
    site_data = defaultdict(lambda: {"n_ref": 0, "n_deam": 0, "context": None})

    read_count = skip_count = 0

    with bs.AlignmentFile(bam_path, "rb") as bam:

        chroms_to_use = get_chromosomes_from_header(bam, chromosomes)
        print(f"Processing chromosomes: {chroms_to_use if chroms_to_use else 'ALL'}")
        print("Reading BAM... (may take several minutes for large files)\n")

        for read in bam:

            flag = read.flag
            if flag & 0x4:   skip_count += 1; continue
            if flag & 0x100: skip_count += 1; continue
            if flag & 0x200: skip_count += 1; continue
            if flag & 0x400: skip_count += 1; continue

            try:
                mapq = read.mapq
            except AttributeError:
                try:
                    mapq = read.mapping_quality
                except AttributeError:
                    mapq = 0
            if mapq < min_mq:
                skip_count += 1; continue

            if read.cigar is None:
                skip_count += 1; continue

            try:
                chrom = read.reference_name
            except AttributeError:
                try:
                    chrom = read.rname
                except AttributeError:
                    continue

            if chroms_to_use and chrom not in chroms_to_use:
                continue

            seq       = read.query_sequence
            qualities = read.query_qualities
            if seq is None or qualities is None:
                continue

            read_count += 1
            if read_count % 200_000 == 0:
                print(f"  {read_count:,} reads processed, "
                      f"{len(site_data):,} cytosine sites accumulated...")

            is_reverse = bool(flag & 0x10)

            try:
                pairs = parse_cigar(read)
            except Exception:
                continue

            for q_idx, r_pos in pairs:
                if q_idx >= len(seq) or q_idx >= len(qualities):
                    continue
                if qualities[q_idx] < min_bq:
                    continue

                read_base = seq[q_idx].upper()

                try:
                    ref_base = str(fasta[chrom][r_pos]).upper()
                except Exception:
                    continue

                # A read is only informative about a given reference C (or G)
                # if it actually derives from the strand that physically has a
                # cytosine at this coordinate. A read from the OPPOSITE strand
                # covering the same position has no C there at all (it has the
                # complementary base), so an unconverted copy of it will
                # always display the reference base after standard SAM
                # reverse-complementing -- it can never show a "converted"
                # signal, and including it would only pad the coverage
                # denominator without ever contributing to the deaminated
                # count. Gate on the read's own alignment strand (FLAG 0x10)
                # to exclude these uninformative reads entirely.
                if ref_base == "C" and not is_reverse and read_base in ("C", "T"):
                    key = (chrom, r_pos, "+")
                    if site_data[key]["context"] is None:
                        ctx = fetch_context(fasta, chrom, r_pos, flank_size)
                        if ctx is None:
                            continue
                        site_data[key]["context"] = ctx
                    if read_base == "T":
                        site_data[key]["n_deam"] += 1
                    else:
                        site_data[key]["n_ref"] += 1

                elif ref_base == "G" and is_reverse and read_base in ("G", "A"):
                    key = (chrom, r_pos, "-")
                    if site_data[key]["context"] is None:
                        ctx_plus = fetch_context(fasta, chrom, r_pos, flank_size)
                        if ctx_plus is None:
                            continue
                        site_data[key]["context"] = reverse_complement(ctx_plus)
                    if read_base == "A":
                        site_data[key]["n_deam"] += 1
                    else:
                        site_data[key]["n_ref"] += 1

    print(f"\n  Reads processed : {read_count:,}")
    print(f"  Reads skipped   : {skip_count:,}")
    print(f"  Raw sites found : {len(site_data):,}")

    center_idx = flank_size
    plus1_idx  = flank_size + 1

    records = []
    for (chrom, pos, strand), v in site_data.items():
        total = v["n_ref"] + v["n_deam"]
        if total < min_cov or v["context"] is None:
            continue
        ctx = v["context"]
        records.append({
            "chrom"          : chrom,
            "pos"            : pos,
            "strand"         : strand,
            "reference"      : "C" if strand == "+" else "G",
            "coverage"       : total,
            "n_deaminated"   : v["n_deam"],
            "n_ref"          : v["n_ref"],
            "conv_rate"      : v["n_deam"] / total,
            "context"        : ctx,
            "context_plus1"  : ctx[plus1_idx],
        })

    df = pd.DataFrame(records)
    print(f"  Sites passing coverage >= {min_cov}: {len(df):,}")
    if len(df):
        print(f"  Total deamination observations (sum of n_deaminated): "
              f"{df['n_deaminated'].sum():,}")
    return df


def count_genome_base_composition(ref_path: str, chromosomes: list) -> Counter:
    """
    Whole-genome (or whole-selected-chromosome-set) A/C/G/T base counts,
    scanned directly from the reference FASTA. Independent of the BAM,
    the enzyme reaction, and the +/-flank window used elsewhere in this
    script -- this is simply "how much A, C, G, and T is in the reference
    sequence(s) analysed," so you can apply any composition normalization
    you want by hand to the deamination-weighted results below.
    """
    print("  Scanning reference genome for whole-sequence base composition...")
    fasta  = pyfaidx.Fasta(ref_path)
    chroms = chromosomes if chromosomes else list(fasta.keys())

    counts = Counter()
    for chrom in chroms:
        seq = str(fasta[chrom][:].seq).upper()
        for base in BASES:
            counts[base] += seq.count(base)
        print(f"    {chrom}: {len(seq):,} bp")

    total = sum(counts.values())
    print(f"  Total A/C/G/T bases counted: {total:,}")
    return counts


def count_genomic_position_composition(ref_path: str,
                                        chromosomes: list,
                                        flank_size: int) -> Counter:
    """
    Scan the reference FASTA and count the full (2*flank_size+1)-mer
    context around every genomic C (using the reverse complement around
    every genomic G, so everything is oriented 5'->3' with C at the
    centre). This is purely descriptive genomic-composition information --
    it is reported alongside the deamination-weighted heatmap/logo so you
    can normalize by hand if desired, but it is NOT used to correct or
    rescale any of the deamination-weighted results in this script.
    """
    print("  Scanning reference genome for cytosine-window context counts...")
    fasta  = pyfaidx.Fasta(ref_path)
    window = 2 * flank_size + 1

    full_window_counts = Counter()
    chroms = chromosomes if chromosomes else list(fasta.keys())

    for chrom in chroms:
        seq       = str(fasta[chrom][:].seq).upper()
        chrom_len = len(seq)
        print(f"    {chrom}: {chrom_len:,} bp", end=" ... ")

        fwd_count = rev_count = 0
        for pos in range(flank_size, chrom_len - flank_size):
            base = seq[pos]
            if base == "C":
                ctx = seq[pos - flank_size: pos + flank_size + 1]
                if len(ctx) == window and "N" not in ctx:
                    full_window_counts[ctx] += 1
                    fwd_count += 1
            elif base == "G":
                ctx_plus = seq[pos - flank_size: pos + flank_size + 1]
                if len(ctx_plus) == window and "N" not in ctx_plus:
                    ctx_rc = ctx_plus.translate(COMPLEMENT)[::-1]
                    full_window_counts[ctx_rc] += 1
                    rev_count += 1

        print(f"{fwd_count:,} fwd C + {rev_count:,} rev C")

    total = sum(full_window_counts.values())
    print(f"  Total genomic cytosine-window contexts counted: {total:,}")
    return full_window_counts


def genomic_position_base_counts(full_window_counts: Counter, flank_size: int) -> dict:
    """
    Marginal genomic base count at each flanking position (-flank_size to
    +flank_size, skipping 0), derived from the full-window context counts
    above. Purely descriptive/reference information for manual
    normalization -- not used to correct any plotted value.
    """
    window = 2 * flank_size + 1
    pos_counts = {}
    for rel_pos in range(-flank_size, flank_size + 1):
        if rel_pos == 0:
            continue
        char_idx = rel_pos + flank_size
        counts = Counter()
        for ctx, n in full_window_counts.items():
            if len(ctx) == window:
                counts[ctx[char_idx]] += n
        pos_counts[rel_pos] = {b: counts.get(b, 0) for b in BASES}
    return pos_counts


print("Cell 1 loaded: imports, config, and helper functions ready.")
print(f"BAM_FILE:   {BAM_FILE}")
print(f"REF_FASTA:  {REF_FASTA}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")


# %% CELL 2 — Collect per-site counts from the BAM + scan the reference genome
# This is the slow cell (reads the whole BAM and the whole reference once).
# Re-run this only if you change BAM_FILE / REF_FASTA / CHROMOSOMES / the
# read-filtering config in Cell 1.

for path, label in [(BAM_FILE, "BAM_FILE"), (REF_FASTA, "REF_FASTA")]:
    if not os.path.exists(path):
        sys.exit(f"\nERROR: {label} not found:\n  {path}\n"
                 "Please set the correct path in Cell 1's CONFIG section.")

make_output_dir(OUTPUT_DIR)

df_sites = collect_sites(
    bam_path    = BAM_FILE,
    ref_path    = REF_FASTA,
    chromosomes = CHROMOSOMES,
    flank_size  = FLANK_SIZE,
    min_bq      = MIN_BASE_QUALITY,
    min_mq      = MIN_MAPPING_QUAL,
    min_cov     = MIN_COVERAGE,
)

if df_sites.empty:
    sys.exit("\nERROR: No cytosine sites collected. "
             "Check BAM/FASTA paths, chromosome names, and MIN_COVERAGE.")

print("\n" + "="*60)
print("Scanning reference genome for base composition")
print("="*60)
genome_base_counts = count_genome_base_composition(REF_FASTA, CHROMOSOMES)
full_window_counts = count_genomic_position_composition(REF_FASTA, CHROMOSOMES, FLANK_SIZE)

print("\nCell 2 complete. df_sites, genome_base_counts, and full_window_counts "
      "are ready in the workspace -- run Cell 3.")


# %% CELL 3 — Compute weighted frequencies, generate plots, export files
# Requires Cell 2 to have been run first (uses df_sites, genome_base_counts,
# full_window_counts). Safe to re-run on its own if you only change
# plotting/export code below.

if "df_sites" not in dir():
    sys.exit("\nERROR: `df_sites` not found. Run Cell 2 first.")


def compute_weighted_position_frequencies(df_sites: pd.DataFrame,
                                           flank_size: int) -> pd.DataFrame:
    """
    Per-position base frequency among ALL observed C->T (or G->A)
    deamination events, weighted by how many times each site was observed
    to be deaminated (n_deaminated). A site with 11 of 40 reads showing
    conversion contributes 11 counts at every flanking position; a site
    with 1 of 23 contributes 1 count. The denominator at every position is
    therefore the total number of deamination observations
    (df_sites['n_deaminated'].sum()), so freq sums to 1.0 across the 4
    bases at each position.

    No genomic-composition correction is applied -- these are the raw
    observed frequencies. See the reference-genome base-composition
    workbook to normalize by hand if desired.
    """
    window       = 2 * flank_size + 1
    total_deam   = int(df_sites["n_deaminated"].sum())
    positions    = [p for p in range(-flank_size, flank_size + 1) if p != 0]

    records = []
    for rel_pos in positions:
        char_idx = rel_pos + flank_size
        weighted_count = Counter()
        for ctx, w in zip(df_sites["context"], df_sites["n_deaminated"]):
            if isinstance(ctx, str) and len(ctx) == window and w > 0:
                weighted_count[ctx[char_idx]] += w
        for base in BASES:
            wc = weighted_count.get(base, 0)
            records.append({
                "position"       : rel_pos,
                "base"           : base,
                "weighted_count" : wc,
                "total_weight"   : total_deam,
                "freq"           : (wc / total_deam) if total_deam > 0 else 0.0,
            })

    return pd.DataFrame(records)


def compute_composition_corrected_frequencies(freq_df: pd.DataFrame,
                                               full_window_counts: Counter,
                                               flank_size: int) -> pd.DataFrame:
    """
    OPTIONAL (plots 09b/10b) -- rescales the raw deamination-weighted
    frequencies in freq_df to remove the genome's own base composition at
    each flanking position, i.e. "as if every base were equally
    represented in the genome at that position."

    For each (position, base):
        p_obs   = observed deamination-weighted frequency (freq_df['freq'])
        p_bg    = genomic background frequency at that position, i.e. how
                  often that base appears at that flanking position across
                  every genomic C (or reverse-complemented G) window --
                  the same population the observed sites are drawn from
        ratio   = p_obs / p_bg   (1.0 = no enrichment; >1 = enriched;
                  <1 = depleted, relative to genome background)
        p_corr  = ratio / sum(ratio over the 4 bases at that position)
                  (renormalized so the 4 bases sum back to 1.0 at each
                  position, giving a value directly usable as a bar/letter
                  height, exactly as freq_df['freq'] is for the
                  uncorrected plots 09/10)

    This does not modify freq_df or the underlying site data -- it is a
    separate, optional rescaling used only for plots 09b/10b.
    """
    pos_base_counts = genomic_position_base_counts(full_window_counts, flank_size)
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]

    records = []
    ratios_by_pos = {}
    for rel_pos in positions:
        total_genomic = sum(pos_base_counts[rel_pos].values())
        ratios = {}
        for base in BASES:
            p_obs = freq_df[(freq_df["position"] == rel_pos) &
                             (freq_df["base"] == base)]["freq"].values[0]
            genomic_count = pos_base_counts[rel_pos][base]
            p_bg = (genomic_count / total_genomic) if total_genomic > 0 else 0.0
            ratios[base] = (p_obs / p_bg) if p_bg > 0 else 0.0
        ratios_by_pos[rel_pos] = ratios

    for rel_pos in positions:
        ratios = ratios_by_pos[rel_pos]
        ratio_sum = sum(ratios.values())
        for base in BASES:
            p_obs = freq_df[(freq_df["position"] == rel_pos) &
                             (freq_df["base"] == base)]["freq"].values[0]
            genomic_count = pos_base_counts[rel_pos][base]
            total_genomic = sum(pos_base_counts[rel_pos].values())
            p_bg = (genomic_count / total_genomic) if total_genomic > 0 else 0.0
            ratio = ratios[base]
            p_corr = (ratio / ratio_sum) if ratio_sum > 0 else 0.0
            records.append({
                "position"          : rel_pos,
                "base"              : base,
                "freq_observed"     : p_obs,
                "freq_genomic_bg"   : p_bg,
                "enrichment_ratio"  : ratio,
                "freq_corrected"    : p_corr,
            })

    return pd.DataFrame(records)


def compute_dinucleotide_context_rates(df_sites: pd.DataFrame) -> pd.DataFrame:
    """
    % C->T conversion broken out by the +1 sequence context (CpG / CpA /
    CpC / CpT). For each class: denominator = total read coverage summed
    across every covered site in that class; numerator = total C->T (or
    G->A) observations summed across those same sites. This is a
    coverage-weighted conversion rate per dinucleotide class, using every
    covered site regardless of whether it showed any conversion.
    """
    rows = []
    for ctx_name in DINUC_CONTEXTS:
        base = DINUC_BASE_OF[ctx_name]
        sub  = df_sites[df_sites["context_plus1"] == base]
        n_sites   = len(sub)
        total_cov = int(sub["coverage"].sum())
        total_dea = int(sub["n_deaminated"].sum())
        pct = 100.0 * total_dea / total_cov if total_cov > 0 else 0.0
        rows.append({
            "context"          : ctx_name,
            "n_sites"          : n_sites,
            "total_coverage"   : total_cov,
            "total_deaminated" : total_dea,
            "pct_C_to_T"       : pct,
        })
    return pd.DataFrame(rows)


print("\n" + "="*60)
print("Computing deamination-weighted position-specific nucleotide frequencies")
print("="*60)
freq_df = compute_weighted_position_frequencies(df_sites, FLANK_SIZE)

if GENERATE_COMPOSITION_CORRECTED:
    print("\n" + "="*60)
    print("Computing composition-corrected position frequencies (09b/10b)")
    print("="*60)
    corrected_df = compute_composition_corrected_frequencies(freq_df, full_window_counts, FLANK_SIZE)

print("\n" + "="*60)
print("Computing % C->T conversion by +1 dinucleotide context")
print("="*60)
dinuc_df = compute_dinucleotide_context_rates(df_sites)
print(dinuc_df.to_string(index=False))


# ── Plotting ──────────────────────────────────────────────────────────────

def plot_position_frequency_heatmap(freq_df: pd.DataFrame, flank_size: int, out_dir: str):
    """
    PLOT 09 — Deamination-observation-weighted base frequency at each
    flanking position (-3 to +3, skipping 0). No genomic-composition
    correction is applied; the color scale is simply centred at 0.25 as a
    visual reference for "equal representation of all 4 bases," which is
    only the correct "no preference" baseline if the genome itself has an
    even base composition at that position (see the reference-genome
    base-composition workbook).
    """
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]
    mat = np.zeros((4, len(positions)))
    for j, pos in enumerate(positions):
        sub = freq_df[freq_df["position"] == pos]
        for i, base in enumerate(BASES):
            val = sub[sub["base"] == base]["freq"]
            mat[i, j] = val.values[0] if len(val) else 0.0

    # Figure size in inches -- this is the main lever for the plot's overall
    # printed size (each box's physical size = figsize / grid dimensions,
    # after axes/label/colorbar margins). Shrink this to make the whole
    # plot (and every box in it) smaller.
    fig, ax = plt.subplots(figsize=(5.5, 2.3))
    cmap = plt.cm.RdBu_r
    # Color scale fixed to 0-1 regardless of the data, so multiple samples
    # plotted separately always share the same scale and are directly
    # comparable. (Previously this adapted to the data: vmax = max(0.5,
    # mat.max()), so two samples could end up on different scales.)
    norm = TwoSlopeNorm(vmin=0.0, vcenter=0.25, vmax=1.0)

    # Draw the heatmap as individual colored rectangles rather than
    # ax.imshow(), so it stays vector (editable) in PDF output rather than
    # importing as a single embedded raster image.
    # box_pad shrinks each box below the full 1x1 grid cell, leaving a
    # visible gap between adjacent boxes. 0.0 = boxes touch edge-to-edge;
    # a thin black border (rather than white) keeps adjacent similar-
    # valued boxes visually distinct even with zero gap between them.
    box_pad = 0.0
    box_w = box_h = 1 - box_pad
    n_rows = mat.shape[0]
    total_cols = 2 * flank_size + 1  # includes an empty column for position 0
    for i in range(n_rows):
        for j, pos in enumerate(positions):
            col = pos + flank_size  # skips column index flank_size (position 0)
            color = cmap(norm(mat[i, j]))
            ax.add_patch(mpatches.Rectangle(
                (col - box_w / 2, i - box_h / 2), box_w, box_h,
                facecolor=color, edgecolor="black", linewidth=0.25))
            val = mat[i, j]
            text_color = "black" if 0.15 < val < 0.40 else "white"
            ax.text(col, i, f"{val:.2f}", ha="center", va="center",
                    fontsize=8, color=text_color, fontweight="bold")

    # Position 0 is deliberately left as an empty gap column (no box drawn)
    # for a C -> U indicator to be added manually in Illustrator, matching
    # the gap already present at position 0 in plots 10/10b.
    ax.set_xlim(-0.5, total_cols - 0.5)
    ax.set_ylim(n_rows - 0.5, -0.5)
    ax.set_xticks(range(total_cols))
    ax.set_xticklabels([str(p) for p in range(-flank_size, flank_size + 1)], fontsize=10)
    ax.set_yticks(range(4))
    ax.set_yticklabels(BASES, fontsize=10)
    ax.set_xlabel("Position relative to deaminated C (0)", fontsize=10)
    ax.set_ylabel("Nucleotide", fontsize=10)
    # Mirror the left/bottom axis spines on the top/right so the heatmap
    # is fully enclosed in a rectangular border (same default weight/color
    # as the existing spines, not a separately-styled line).
    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, fraction=0.03, pad=0.02)
    # Explicit ticks so 0.1 and 0.25 land at their correct (non-linear,
    # TwoSlopeNorm) positions alongside the standard 0.2-spaced values.
    cbar.set_ticks([0.0, 0.1, 0.2, 0.25, 0.4, 0.6, 0.8, 1.0])
    cbar.ax.tick_params(labelsize=8)
    cbar.ax.axhline(0.25, color="black", linewidth=1.5, linestyle="--")
    # No colorbar label and no plot title -- trimmed for a more compact,
    # Illustrator-ready default output.

    plt.tight_layout()
    path = os.path.join(out_dir, "09_position_frequency_heatmap.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {path}")


def plot_position_frequency_heatmap_corrected(corrected_df: pd.DataFrame,
                                               flank_size: int, out_dir: str):
    """
    PLOT 09b (OPTIONAL) — Same as plot 09, but each position's base
    frequencies have been divided by that position's own genomic
    background frequency and renormalized to sum to 1 -- i.e. "as if
    every base were equally represented in the genome at that position."
    A value of 0.25 here means no enrichment relative to genome
    background; deviations from 0.25 reflect the enzyme's actual context
    preference rather than the genome's own composition. See
    compute_composition_corrected_frequencies() for the exact calculation.
    """
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]
    mat = np.zeros((4, len(positions)))
    for j, pos in enumerate(positions):
        sub = corrected_df[corrected_df["position"] == pos]
        for i, base in enumerate(BASES):
            val = sub[sub["base"] == base]["freq_corrected"]
            mat[i, j] = val.values[0] if len(val) else 0.0

    fig, ax = plt.subplots(figsize=(5.5, 2.3))
    cmap = plt.cm.RdBu_r
    norm = TwoSlopeNorm(vmin=0.0, vcenter=0.25, vmax=1.0)

    box_pad = 0.0
    box_w = box_h = 1 - box_pad
    n_rows = mat.shape[0]
    total_cols = 2 * flank_size + 1  # includes an empty column for position 0
    for i in range(n_rows):
        for j, pos in enumerate(positions):
            col = pos + flank_size  # skips column index flank_size (position 0)
            color = cmap(norm(mat[i, j]))
            ax.add_patch(mpatches.Rectangle(
                (col - box_w / 2, i - box_h / 2), box_w, box_h,
                facecolor=color, edgecolor="black", linewidth=0.25))
            val = mat[i, j]
            text_color = "black" if 0.15 < val < 0.40 else "white"
            ax.text(col, i, f"{val:.2f}", ha="center", va="center",
                    fontsize=8, color=text_color, fontweight="bold")

    # Position 0 is deliberately left as an empty gap column (no box drawn)
    # for a C -> U indicator to be added manually in Illustrator, matching
    # the gap already present at position 0 in plots 10/10b.
    ax.set_xlim(-0.5, total_cols - 0.5)
    ax.set_ylim(n_rows - 0.5, -0.5)
    ax.set_xticks(range(total_cols))
    ax.set_xticklabels([str(p) for p in range(-flank_size, flank_size + 1)], fontsize=10)
    ax.set_yticks(range(4))
    ax.set_yticklabels(BASES, fontsize=10)
    ax.set_xlabel("Position relative to deaminated C (0)", fontsize=10)
    ax.set_ylabel("Nucleotide", fontsize=10)
    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)

    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, fraction=0.03, pad=0.02)
    cbar.set_ticks([0.0, 0.1, 0.2, 0.25, 0.4, 0.6, 0.8, 1.0])
    cbar.ax.tick_params(labelsize=8)
    cbar.ax.axhline(0.25, color="black", linewidth=1.5, linestyle="--")
    # No colorbar label and no plot title -- trimmed for a more compact,
    # Illustrator-ready default output.

    plt.tight_layout()
    path = os.path.join(out_dir, "09b_position_frequency_heatmap_corrected.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {path}")


_LOGO_LETTER_FONT = FontProperties(family="Arial", weight="bold")


def _add_logo_letter(ax, letter: str, x: float, y0: float, height: float,
                      width: float, color: str):
    """
    Draw a single letter as a filled glyph path, non-uniformly scaled to
    exactly fill a width x height box centred at x with its bottom edge at
    y0. This is what makes the letter itself act as the colored "bar" —
    as in a traditional sequence logo — rather than a colored rectangle
    with a small text label on top of it.
    """
    if height <= 0:
        return
    tp = TextPath((0, 0), letter, size=1, prop=_LOGO_LETTER_FONT)
    bbox = tp.get_extents()
    if bbox.width == 0 or bbox.height == 0:
        return
    transform = (Affine2D()
                 .translate(-bbox.x0, -bbox.y0)
                 .scale(width / bbox.width, height / bbox.height)
                 .translate(x - width / 2, y0)
                 + ax.transData)
    ax.add_patch(PathPatch(tp, transform=transform, facecolor=color,
                            edgecolor="none", lw=0))


def plot_sequence_logo(freq_df: pd.DataFrame, flank_size: int, out_dir: str):
    """
    PLOT 10 — Letter-glyph sequence logo of ALL observed C->T deamination
    events, weighted by how many times each site was observed deaminated
    (n_deaminated). Bar/letter heights are the plain observed frequency at
    each position (freq_df['freq'], which sums to 1.0 across A/C/G/T at
    every position) -- no information-content rescaling and no genomic-
    composition correction, so every column always stacks to a full height
    of 1.0. Bases are always stacked in the same fixed vertical order
    (T bottom, G, C, A top) and colored with the standard Sanger/ABI trace
    convention.
    """
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]

    fig, ax = plt.subplots(figsize=(1.05 * (2 * flank_size + 1) + 1, 4.2))
    letter_width = 0.82
    gap_frac = 0.03  # small visual gap between stacked letters

    for pos in positions:
        sub = freq_df[freq_df["position"] == pos]
        freqs = {b: (sub[sub["base"] == b]["freq"].values[0]
                     if len(sub[sub["base"] == b]) else 0.0) for b in BASES}

        bottom = 0.0
        for base in LOGO_STACK_ORDER_BOTTOM_TO_TOP:
            h = freqs[base]
            if h <= 0:
                continue
            gap = h * gap_frac
            _add_logo_letter(ax, base, pos, bottom + gap / 2, h - gap,
                             letter_width, SANGER_BASE_COLORS[base])
            bottom += h

    # Position 0: fixed C -> U marker (not data-derived -- every counted
    # observation is, by construction, a C converting to a T/U read).
    ax.text(0, 0.72, "C", ha="center", va="center", fontsize=22,
            fontweight="bold", color="black")
    ax.annotate("", xy=(0, 0.30), xytext=(0, 0.58),
                arrowprops=dict(arrowstyle="-|>", color="black", lw=2))
    ax.text(0, 0.14, "U", ha="center", va="center", fontsize=22,
            fontweight="bold", color="black")

    all_x = list(range(-flank_size, flank_size + 1))
    ax.set_xticks(all_x)
    ax.set_xticklabels([str(p) for p in all_x], fontsize=11)
    ax.set_xlim(-flank_size - 0.6, flank_size + 0.6)
    ax.set_ylim(0, 1.0)
    ax.set_ylabel("Deamination-weighted frequency", fontsize=12)
    ax.set_xlabel("Position relative to deaminated C", fontsize=12)
    ax.set_title(
        "Sequence Logo — All Observed C→T Deamination Events\n"
        "(height scaled to observed frequency; weighted by n_deaminated per site)",
        fontsize=12, fontweight="bold")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()
    path = os.path.join(out_dir, "10_sequence_logo.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {path}")


def plot_sequence_logo_corrected(corrected_df: pd.DataFrame, flank_size: int, out_dir: str):
    """
    PLOT 10b (OPTIONAL) — Same as plot 10, but stacked using
    freq_corrected instead of the raw observed freq: each position's
    values have been divided by that position's genomic background
    frequency and renormalized to sum to 1, so bases are shown "as if
    every base were equally represented in the genome at that position."
    """
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]

    fig, ax = plt.subplots(figsize=(1.05 * (2 * flank_size + 1) + 1, 4.2))
    letter_width = 0.82
    gap_frac = 0.03

    for pos in positions:
        sub = corrected_df[corrected_df["position"] == pos]
        freqs = {b: (sub[sub["base"] == b]["freq_corrected"].values[0]
                     if len(sub[sub["base"] == b]) else 0.0) for b in BASES}

        bottom = 0.0
        for base in LOGO_STACK_ORDER_BOTTOM_TO_TOP:
            h = freqs[base]
            if h <= 0:
                continue
            gap = h * gap_frac
            _add_logo_letter(ax, base, pos, bottom + gap / 2, h - gap,
                             letter_width, SANGER_BASE_COLORS[base])
            bottom += h

    ax.text(0, 0.72, "C", ha="center", va="center", fontsize=22,
            fontweight="bold", color="black")
    ax.annotate("", xy=(0, 0.30), xytext=(0, 0.58),
                arrowprops=dict(arrowstyle="-|>", color="black", lw=2))
    ax.text(0, 0.14, "U", ha="center", va="center", fontsize=22,
            fontweight="bold", color="black")

    all_x = list(range(-flank_size, flank_size + 1))
    ax.set_xticks(all_x)
    ax.set_xticklabels([str(p) for p in all_x], fontsize=11)
    ax.set_xlim(-flank_size - 0.6, flank_size + 0.6)
    ax.set_ylim(0, 1.0)
    ax.set_ylabel("Composition-corrected frequency", fontsize=12)
    ax.set_xlabel("Position relative to deaminated C", fontsize=12)
    ax.set_title(
        "Sequence Logo — Composition-Corrected\n"
        "(each position divided by its own genomic background, renormalized to sum to 1)",
        fontsize=12, fontweight="bold")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()
    path = os.path.join(out_dir, "10b_sequence_logo_corrected.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {path}")


def plot_dinucleotide_context(dinuc_df: pd.DataFrame, out_dir: str):
    """
    PLOT 11 — % C->T conversion by +1 sequence context (CpG / CpA / CpC /
    CpT). For each class, all covered-site coverage in that class is the
    denominator and all C->T observations in that class are the numerator.
    """
    order = DINUC_CONTEXTS
    sub = dinuc_df.set_index("context").loc[order].reset_index()
    colors = [BASE_COLORS[DINUC_BASE_OF[c]] for c in order]

    fig, ax = plt.subplots(figsize=(6.5, 5))
    bars = ax.bar(sub["context"], sub["pct_C_to_T"], color=colors,
                  edgecolor="white", linewidth=0.6, width=0.6)
    for bar, (_, row) in zip(bars, sub.iterrows()):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(),
                f"{row['pct_C_to_T']:.2f}%\n(n={row['total_coverage']:,})",
                ha="center", va="bottom", fontsize=9)

    ax.set_ylabel("% C→T conversion (deaminated reads / total coverage)", fontsize=12)
    ax.set_xlabel("+1 sequence context", fontsize=12)
    ax.set_title("% C→T Deamination by +1 Sequence Context", fontsize=13, fontweight="bold")
    ax.set_ylim(0, max(sub["pct_C_to_T"].max() * 1.25, 1.0))
    plt.tight_layout()
    path = os.path.join(out_dir, "11_dinucleotide_context_conversion.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.show()
    print(f"  Saved: {path}")


print("\n" + "="*60)
print("Generating plots")
print("="*60)
plot_position_frequency_heatmap(freq_df, FLANK_SIZE, OUTPUT_DIR)
plot_sequence_logo(freq_df, FLANK_SIZE, OUTPUT_DIR)
plot_dinucleotide_context(dinuc_df, OUTPUT_DIR)

if GENERATE_COMPOSITION_CORRECTED:
    plot_position_frequency_heatmap_corrected(corrected_df, FLANK_SIZE, OUTPUT_DIR)
    plot_sequence_logo_corrected(corrected_df, FLANK_SIZE, OUTPUT_DIR)


# ── CSV export ────────────────────────────────────────────────────────────

def save_results(df_sites: pd.DataFrame, dinuc_df: pd.DataFrame, out_dir: str):
    files = {
        "site_deamination_data.csv"           : df_sites,
        "dinucleotide_context_conversion.csv" : dinuc_df,
    }
    print("CSV files saved:")
    for fname, data in files.items():
        path = os.path.join(out_dir, fname)
        data.to_csv(path, index=False)
        print(f"  {path}")


print("\n" + "="*60)
print("Saving CSV results")
print("="*60)
save_results(df_sites, dinuc_df, OUTPUT_DIR)


# =============================================================================
# EXCEL EXPORT — underlying data + live formulas
# =============================================================================
# These workbooks contain the same raw source data that feeds each plot,
# plus the actual calculations (as live Excel formulas, not just static
# numbers) that turn that raw data into the plotted values. Source data is
# shown in blue text, formulas/calculations in black text, matching the
# convention on each workbook's Notes sheet.

_HEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF")
_HEADER_FILL = PatternFill("solid", start_color="4472C4")
_INPUT_FONT  = Font(name="Arial", color="0000FF")
_CALC_FONT   = Font(name="Arial", color="000000")
_NOTE_FONT   = Font(name="Arial", italic=True, size=9, color="666666")
_TITLE_FONT  = Font(name="Arial", bold=True, size=11)


def _xl_style_headers(ws, row, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(horizontal="center")


def _xl_autosize(ws, ncols, width=14):
    for c in range(1, ncols + 1):
        ws.column_dimensions[get_column_letter(c)].width = width


def _xl_write_notes(ws, notes: list):
    for i, line in enumerate(notes, start=1):
        ws.cell(i, 1, line).font = _TITLE_FONT if i == 1 else _NOTE_FONT
    ws.column_dimensions["A"].width = 100


def export_site_data_excel(df_sites: pd.DataFrame, flank_size: int, out_dir: str):
    """
    "site_vs_control"-style per-site data table. Every column here describes the
    enzyme treated sample. Columns: chrom, position, strand, coverage,
    deaminated, reference, conversion rate, context, and (new) the +1
    sequence context immediately after the context column.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Site_Data"

    headers = ["chrom", "position", "strand", "coverage", "deaminated",
               "reference", "conversion rate", "context", "+1 context"]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))

    plus1_char_idx = flank_size + 2  # 1-based MID() index of the +1 base

    for i, row in enumerate(df_sites.itertuples(index=False), start=2):
        ws.cell(i, 1, row.chrom)
        ws.cell(i, 2, row.pos)
        ws.cell(i, 3, row.strand)
        ws.cell(i, 4, row.coverage).font = _INPUT_FONT
        ws.cell(i, 5, row.n_deaminated).font = _INPUT_FONT
        ws.cell(i, 6, row.reference).font = _INPUT_FONT
        ws.cell(i, 7, f"=IF(D{i}=0,0,E{i}/D{i})").font = _CALC_FONT
        ws.cell(i, 8, row.context).font = _INPUT_FONT
        ws.cell(i, 9, f"=MID(H{i},{plus1_char_idx},1)").font = _CALC_FONT

    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Site_Data -- per-site deamination calls, treated sample only",
        "",
        "Every covered reference C (or G, minus strand) site is kept as long as it has",
        "  coverage >= MIN_COVERAGE, and every C->T (or G->A) read at that site is",
        "  counted directly as a deamination event. No rate threshold or control",
        "  subtraction is applied.",
        "",
        "coverage = total reads at this site (n_ref + deaminated).",
        "deaminated = number of reads showing the converted base (T on + strand,",
        "  A on - strand) at this site.",
        "reference = the reference base at this genomic position (C on + strand,",
        "  G on - strand).",
        "conversion rate = deaminated / coverage.",
        "context = the (2*FLANK_SIZE+1)-mer reference sequence centred on this site,",
        "  oriented 5'->3' with the reference C at the centre (reverse-complemented",
        "  already for minus-strand sites).",
        "+1 context = the single base immediately 3' of the centre C in the context",
        "  string above (e.g. context 'AGTCGTA' -> +1 context 'G').",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "site_vs_control.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def _xl_write_weighted_sites_sheet(ws, df_sites: pd.DataFrame, flank_size: int):
    """
    Shared helper: writes a self-contained "Sites" sheet (chrom, pos,
    strand, context, weight=deaminated) with one MID() formula column per
    flanking position, used by both the plot 09 and plot 10 workbooks to
    compute deamination-weighted position frequencies.
    """
    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]
    headers = ["chrom", "pos", "strand", "context", "weight_deaminated"] + \
              [f"base_at_{p:+d}" for p in positions]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))

    for i, row in enumerate(df_sites.itertuples(index=False), start=2):
        ws.cell(i, 1, row.chrom)
        ws.cell(i, 2, row.pos)
        ws.cell(i, 3, row.strand)
        ws.cell(i, 4, row.context).font = _INPUT_FONT
        ws.cell(i, 5, row.n_deaminated).font = _INPUT_FONT
        for j, p in enumerate(positions):
            char_idx = (p + flank_size) + 1  # 1-based MID() index into context string
            ws.cell(i, 6 + j, f"=MID(D{i},{char_idx},1)").font = _CALC_FONT

    n_sites = len(df_sites)
    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"
    return n_sites, positions


def _xl_write_position_frequencies_sheet(ws, positions: list, n_sites: int, sheet_name: str = "Sites"):
    headers = ["position", "base", "weighted_count", "total_weight", "freq"]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))

    weight_range = f"'{sheet_name}'!$E$2:$E${n_sites + 1}"
    base_col_letters = {p: get_column_letter(6 + j) for j, p in enumerate(positions)}

    r = 2
    first_row_of_pos = {}
    for p in positions:
        first_row_of_pos[p] = r
        col = base_col_letters[p]
        pos_range = f"'{sheet_name}'!${col}$2:${col}${n_sites + 1}"
        for b in BASES:
            ws.cell(r, 1, p)
            ws.cell(r, 2, b)
            ws.cell(r, 3, f'=SUMPRODUCT(({pos_range}="{b}")*({weight_range}))').font = _CALC_FONT
            ws.cell(r, 4, f"=SUM({weight_range})").font = _CALC_FONT
            ws.cell(r, 5, f"=IF(D{r}=0,0,C{r}/D{r})").font = _CALC_FONT
            r += 1

    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"
    return first_row_of_pos


def _xl_write_genomic_position_composition_sheet(ws, pos_base_counts: dict, positions: list):
    headers = ["position", "base", "genomic_count", "total_at_position", "freq_genomic"]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))
    r = 2
    first_row_of_pos = {}
    for p in positions:
        first_row_of_pos[p] = r
        for b in BASES:
            ws.cell(r, 1, p)
            ws.cell(r, 2, b)
            ws.cell(r, 3, pos_base_counts[p][b]).font = _INPUT_FONT
            r += 1
    for p in positions:
        r0 = first_row_of_pos[p]
        for k in range(4):
            r = r0 + k
            ws.cell(r, 4, f"=SUM($C${r0}:$C${r0+3})").font = _CALC_FONT
            ws.cell(r, 5, f"=C{r}/D{r}").font = _CALC_FONT
    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"


def _xl_write_corrected_frequencies_sheet(ws, positions: list):
    """
    Shared helper for the OPTIONAL 09b/10b workbooks. Assumes this same
    workbook already has a "Position_Frequencies" sheet (via
    _xl_write_position_frequencies_sheet) and a "Genomic_Position_
    Composition" sheet (via _xl_write_genomic_position_composition_sheet)
    laid out with identical row ordering (position, then A/C/G/T within
    each position) -- both of those helpers iterate `for p in positions:
    for b in BASES`, so row 2+i*4+j (i = index of p, j = index of base)
    lines up across all three sheets.

    Writes: enrichment_ratio = freq (observed) / freq_genomic (background)
    freq_corrected = enrichment_ratio, renormalized to sum to 1 across the
    4 bases at each position.
    """
    headers = ["position", "base", "freq_observed", "freq_genomic_bg",
               "enrichment_ratio", "freq_corrected"]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))

    r = 2
    first_row_of_pos = {}
    for p in positions:
        first_row_of_pos[p] = r
        for b in BASES:
            ws.cell(r, 1, p)
            ws.cell(r, 2, b)
            ws.cell(r, 3, f"=Position_Frequencies!E{r}").font = _CALC_FONT
            ws.cell(r, 4, f"=Genomic_Position_Composition!E{r}").font = _CALC_FONT
            ws.cell(r, 5, f"=IF(D{r}=0,0,C{r}/D{r})").font = _CALC_FONT
            r += 1
    for p in positions:
        r0 = first_row_of_pos[p]
        for k in range(4):
            r = r0 + k
            ws.cell(r, 6, f"=IF(SUM($E${r0}:$E${r0+3})=0,0,E{r}/SUM($E${r0}:$E${r0+3}))").font = _CALC_FONT

    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"
    return first_row_of_pos


_CORRECTED_NOTES = [
    "freq_observed = the same deamination-weighted frequency as in plots 09/10",
    "  (from the Position_Frequencies sheet).",
    "freq_genomic_bg = how often that base appears at that flanking position",
    "  across every genomic C (or reverse-complemented G) window in the",
    "  reference -- i.e. the background you'd expect if the enzyme had zero",
    "  context preference (from the Genomic_Position_Composition sheet).",
    "enrichment_ratio = freq_observed / freq_genomic_bg. 1.0 = no enrichment",
    "  over genome background; >1 = enriched; <1 = depleted.",
    "freq_corrected = enrichment_ratio, renormalized so the 4 bases sum back",
    "  to 1.0 at each position -- this is 'as if every base were equally",
    "  represented in the genome at that position,' and is the value plotted",
    "  in the heatmap/logo below.",
]


def export_plot9_excel(df_sites: pd.DataFrame, flank_size: int,
                        full_window_counts: Counter, out_dir: str):
    """
    Excel workbook backing PLOT 09 (deamination-weighted position
    frequency heatmap). Sites: one row per covered site, weighted by
    n_deaminated. Position_Frequencies: weighted base frequency at each
    flanking position. Heatmap_Matrix: the same values laid out as a
    base x position grid matching the plotted figure. Genomic_Position_
    Composition: reference-only information (not used in any calculation
    here) so you can normalize by hand if desired.
    """
    wb = Workbook()
    ws_sites = wb.active
    ws_sites.title = "Sites"
    n_sites, positions = _xl_write_weighted_sites_sheet(ws_sites, df_sites, flank_size)

    ws_pf = wb.create_sheet("Position_Frequencies")
    first_row_pf = _xl_write_position_frequencies_sheet(ws_pf, positions, n_sites)

    ws_hm = wb.create_sheet("Heatmap_Matrix")
    ws_hm.cell(1, 1, "base")
    for j, p in enumerate(positions, start=2):
        ws_hm.cell(1, j, p)
    _xl_style_headers(ws_hm, 1, len(positions) + 1)
    for i, b in enumerate(BASES, start=2):
        ws_hm.cell(i, 1, b).font = Font(name="Arial", bold=True)
        for j, p in enumerate(positions, start=2):
            r0 = first_row_pf[p] + BASES.index(b)
            ws_hm.cell(i, j, f"=Position_Frequencies!E{r0}").font = _CALC_FONT
    _xl_autosize(ws_hm, len(positions) + 1)
    rule = ColorScaleRule(start_type="num", start_value=0, start_color="4472C4",
                          mid_type="num", mid_value=0.25, mid_color="FFFFFF",
                          end_type="num", end_value=0.5, end_color="C00000")
    last_col_letter = get_column_letter(len(positions) + 1)
    ws_hm.conditional_formatting.add(f"B2:{last_col_letter}5", rule)

    pos_base_counts = genomic_position_base_counts(full_window_counts, flank_size)
    ws_bg = wb.create_sheet("Genomic_Position_Composition")
    _xl_write_genomic_position_composition_sheet(ws_bg, pos_base_counts, positions)

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Plot 09 -- Deamination-Weighted Position-Specific Base Frequency Heatmap",
        "",
        "Sites: one row per covered site (coverage >= MIN_COVERAGE), all of them --",
        "  not just a subset that passed a threshold. weight_deaminated = number of",
        "  reads at that site showing the converted base. base_at_{pos} pulls the",
        "  base at each flanking position out of the 7-mer context via MID().",
        "",
        "Position_Frequencies: for each (position, base), weighted_count = SUMPRODUCT",
        "  of weight_deaminated across every site whose base at that position matches,",
        "  i.e. a site with weight_deaminated=11 contributes 11 to whichever base is",
        "  at that position for that site. total_weight = sum of weight_deaminated",
        "  across ALL sites (same denominator at every position). freq = weighted_",
        "  count / total_weight; freq sums to 1.0 across A/C/G/T at each position.",
        "",
        "Heatmap_Matrix: the same freq values laid out as a base x position grid,",
        "  matching the layout of the plotted figure. No genomic-composition",
        "  correction is applied anywhere in this workbook.",
        "",
        "Genomic_Position_Composition: reference-only information -- how often each",
        "  base appears at each flanking position across every genomic C (or G) window",
        "  in the reference sequence(s) analysed. This is NOT used to correct any",
        "  value above; it is provided so you can normalize by hand if you want to.",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "09_position_frequency_heatmap_data.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def export_plot10_excel(df_sites: pd.DataFrame, flank_size: int, out_dir: str):
    """
    Excel workbook backing PLOT 10 (letter-glyph sequence logo). Uses the
    same Sites / Position_Frequencies calculation as the plot 09 workbook
    (duplicated here so this file is self-contained) -- the logo's letter
    heights ARE the freq column, stacked directly, with no further
    correction.
    """
    wb = Workbook()
    ws_sites = wb.active
    ws_sites.title = "Sites"
    n_sites, positions = _xl_write_weighted_sites_sheet(ws_sites, df_sites, flank_size)

    ws_pf = wb.create_sheet("Position_Frequencies")
    _xl_write_position_frequencies_sheet(ws_pf, positions, n_sites)

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Plot 10 -- Sequence Logo (all observed C->T deamination events)",
        "",
        "Sites / Position_Frequencies: identical calculation to",
        "  09_position_frequency_heatmap_data.xlsx -- see that file's Notes sheet for",
        "  details. Every covered site (coverage >= MIN_COVERAGE) contributes,",
        "  weighted by weight_deaminated (n_deaminated at that site); there is no",
        "  significance/effect-size threshold and no control BAM.",
        "",
        "The plotted logo's letter height at each position, for each base, is simply",
        "  the freq column from Position_Frequencies -- stacked directly with no",
        "  information-content rescaling and no genomic-composition correction, so",
        "  every column stacks to a full height of 1.0. Bases are always stacked in",
        "  the fixed order T (bottom), G, C, A (top) and colored with the standard",
        "  Sanger/ABI trace convention (A green, C blue, G black, T red).",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "10_sequence_logo_data.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def export_plot9b_excel(df_sites: pd.DataFrame, flank_size: int,
                         full_window_counts: Counter, out_dir: str):
    """
    OPTIONAL — Excel workbook backing PLOT 09b (composition-corrected
    position frequency heatmap). Self-contained: includes the same Sites /
    Position_Frequencies / Genomic_Position_Composition calculation as the
    plot 09 workbook, plus a Corrected_Frequencies sheet with live
    formulas dividing observed by genomic background and renormalizing.
    """
    wb = Workbook()
    ws_sites = wb.active
    ws_sites.title = "Sites"
    n_sites, positions = _xl_write_weighted_sites_sheet(ws_sites, df_sites, flank_size)

    ws_pf = wb.create_sheet("Position_Frequencies")
    _xl_write_position_frequencies_sheet(ws_pf, positions, n_sites)

    pos_base_counts = genomic_position_base_counts(full_window_counts, flank_size)
    ws_bg = wb.create_sheet("Genomic_Position_Composition")
    _xl_write_genomic_position_composition_sheet(ws_bg, pos_base_counts, positions)

    ws_corr = wb.create_sheet("Corrected_Frequencies")
    first_row_corr = _xl_write_corrected_frequencies_sheet(ws_corr, positions)

    ws_hm = wb.create_sheet("Heatmap_Matrix")
    ws_hm.cell(1, 1, "base")
    for j, p in enumerate(positions, start=2):
        ws_hm.cell(1, j, p)
    _xl_style_headers(ws_hm, 1, len(positions) + 1)
    for i, b in enumerate(BASES, start=2):
        ws_hm.cell(i, 1, b).font = Font(name="Arial", bold=True)
        for j, p in enumerate(positions, start=2):
            r0 = first_row_corr[p] + BASES.index(b)
            ws_hm.cell(i, j, f"=Corrected_Frequencies!F{r0}").font = _CALC_FONT
    _xl_autosize(ws_hm, len(positions) + 1)
    rule = ColorScaleRule(start_type="num", start_value=0, start_color="4472C4",
                          mid_type="num", mid_value=0.25, mid_color="FFFFFF",
                          end_type="num", end_value=0.5, end_color="C00000")
    last_col_letter = get_column_letter(len(positions) + 1)
    ws_hm.conditional_formatting.add(f"B2:{last_col_letter}5", rule)

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Plot 09b (OPTIONAL) -- Composition-Corrected Position Frequency Heatmap",
        "",
        "Sites / Position_Frequencies / Genomic_Position_Composition: identical to",
        "  09_position_frequency_heatmap_data.xlsx -- see that file's Notes sheet.",
        "",
        "Corrected_Frequencies:",
    ] + _CORRECTED_NOTES + [
        "",
        "Heatmap_Matrix: freq_corrected laid out as a base x position grid, matching",
        "  the plotted figure. A value of 0.25 means no enrichment relative to genome",
        "  background at that position.",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "09b_position_frequency_heatmap_corrected_data.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def export_plot10b_excel(df_sites: pd.DataFrame, flank_size: int,
                          full_window_counts: Counter, out_dir: str):
    """
    OPTIONAL — Excel workbook backing PLOT 10b (composition-corrected
    sequence logo). Same self-contained calculation as the plot 09b
    workbook; the logo's letter heights ARE the freq_corrected column,
    stacked directly.
    """
    wb = Workbook()
    ws_sites = wb.active
    ws_sites.title = "Sites"
    n_sites, positions = _xl_write_weighted_sites_sheet(ws_sites, df_sites, flank_size)

    ws_pf = wb.create_sheet("Position_Frequencies")
    _xl_write_position_frequencies_sheet(ws_pf, positions, n_sites)

    pos_base_counts = genomic_position_base_counts(full_window_counts, flank_size)
    ws_bg = wb.create_sheet("Genomic_Position_Composition")
    _xl_write_genomic_position_composition_sheet(ws_bg, pos_base_counts, positions)

    ws_corr = wb.create_sheet("Corrected_Frequencies")
    _xl_write_corrected_frequencies_sheet(ws_corr, positions)

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Plot 10b (OPTIONAL) -- Sequence Logo, Composition-Corrected",
        "",
        "Sites / Position_Frequencies / Genomic_Position_Composition: identical to",
        "  09_position_frequency_heatmap_data.xlsx -- see that file's Notes sheet.",
        "",
        "Corrected_Frequencies:",
    ] + _CORRECTED_NOTES + [
        "",
        "The plotted logo's letter height at each position is freq_corrected,",
        "  stacked directly (still sums to 1.0 at every position). Bases are stacked",
        "  in the fixed order T (bottom), G, C, A (top), Sanger/ABI trace colors.",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "10b_sequence_logo_corrected_data.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def export_plot11_excel(df_sites: pd.DataFrame, out_dir: str):
    """
    Excel workbook backing PLOT 11 (% C->T conversion by +1 sequence
    context). Sites: every covered site with its +1 context base.
    Context_Summary: SUMIF totals per CpG/CpA/CpC/CpT class and the
    resulting % conversion.
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Sites"
    headers = ["chrom", "pos", "strand", "coverage", "deaminated", "+1_base", "context_class"]
    ws.append(headers)
    _xl_style_headers(ws, 1, len(headers))

    class_of_base = {v: k for k, v in DINUC_BASE_OF.items()}
    for i, row in enumerate(df_sites.itertuples(index=False), start=2):
        ws.cell(i, 1, row.chrom)
        ws.cell(i, 2, row.pos)
        ws.cell(i, 3, row.strand)
        ws.cell(i, 4, row.coverage).font = _INPUT_FONT
        ws.cell(i, 5, row.n_deaminated).font = _INPUT_FONT
        ws.cell(i, 6, row.context_plus1).font = _INPUT_FONT
        cls = class_of_base.get(row.context_plus1, "")
        ws.cell(i, 7, f'="Cp"&F{i}').font = _CALC_FONT
    n_sites = len(df_sites)
    _xl_autosize(ws, len(headers))
    ws.freeze_panes = "A2"

    ws_s = wb.create_sheet("Context_Summary")
    headers2 = ["context", "n_sites", "total_coverage", "total_deaminated", "pct_C_to_T"]
    ws_s.append(headers2)
    _xl_style_headers(ws_s, 1, len(headers2))
    cov_range   = f"Sites!$D$2:$D${n_sites + 1}"
    deam_range  = f"Sites!$E$2:$E${n_sites + 1}"
    class_range = f"Sites!$G$2:$G${n_sites + 1}"
    for i, ctx_name in enumerate(DINUC_CONTEXTS, start=2):
        ws_s.cell(i, 1, ctx_name)
        ws_s.cell(i, 2, f'=COUNTIF({class_range},A{i})').font = _CALC_FONT
        ws_s.cell(i, 3, f'=SUMIF({class_range},A{i},{cov_range})').font = _CALC_FONT
        ws_s.cell(i, 4, f'=SUMIF({class_range},A{i},{deam_range})').font = _CALC_FONT
        ws_s.cell(i, 5, f'=IF(C{i}=0,0,100*D{i}/C{i})').font = _CALC_FONT
    _xl_autosize(ws_s, len(headers2))
    ws_s.freeze_panes = "A2"

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Plot 11 -- %% C->T Deamination by +1 Sequence Context",
        "",
        "Sites: every covered site (coverage >= MIN_COVERAGE) with its +1 context",
        "  base and derived CpG/CpA/CpC/CpT class.",
        "",
        "Context_Summary: for each class, total_coverage = SUMIF of coverage across",
        "  every site in that class (the denominator -- e.g. total reads covering any",
        "  CpG site); total_deaminated = SUMIF of deaminated reads across those same",
        "  sites (the numerator); pct_C_to_T = 100 * total_deaminated / total_coverage.",
        "",
        "Blue text = source data (from BAM/genome). Black text = formulas/calculations.",
    ])

    path = os.path.join(out_dir, "11_dinucleotide_context_conversion_data.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


def export_genome_composition_excel(genome_base_counts: Counter,
                                     full_window_counts: Counter,
                                     flank_size: int, out_dir: str):
    """
    Standalone workbook reporting the reference genome's own base
    composition, so you can apply any normalization you want to the
    deamination-weighted results by hand. Two views:
      Whole_Genome: A/C/G/T counts and fractions across the entire
        reference sequence(s) analysed (CHROMOSOMES).
      Position_Composition: A/C/G/T counts and fractions at each flanking
        position (-flank_size..+flank_size, skipping 0) across every
        genomic C (or G) window -- i.e. the same position axis as plots
        09/10, for a position-matched normalization reference.
    """
    wb = Workbook()
    ws_wg = wb.active
    ws_wg.title = "Whole_Genome"
    headers = ["base", "count", "fraction"]
    ws_wg.append(headers)
    _xl_style_headers(ws_wg, 1, len(headers))
    total = sum(genome_base_counts.values())
    for i, b in enumerate(BASES, start=2):
        ws_wg.cell(i, 1, b)
        ws_wg.cell(i, 2, genome_base_counts.get(b, 0)).font = _INPUT_FONT
        ws_wg.cell(i, 3, f"=B{i}/SUM($B$2:$B$5)").font = _CALC_FONT
    _xl_autosize(ws_wg, len(headers))

    positions = [p for p in range(-flank_size, flank_size + 1) if p != 0]
    pos_base_counts = genomic_position_base_counts(full_window_counts, flank_size)
    ws_pc = wb.create_sheet("Position_Composition")
    _xl_write_genomic_position_composition_sheet(ws_pc, pos_base_counts, positions)

    ws_n = wb.create_sheet("Notes")
    _xl_write_notes(ws_n, [
        "Reference Genome Base Composition",
        "",
        "Whole_Genome: A/C/G/T counts and fractions across the entire reference",
        "  sequence(s) analysed (all chromosomes if CHROMOSOMES=[] in Cell 1's",
        "  CONFIG, otherwise only the listed chromosomes).",
        "",
        "Position_Composition: A/C/G/T counts and fractions at each flanking position",
        f"  (-{flank_size}..+{flank_size}, skipping 0) across every genomic C (or",
        "  reverse-complemented G) window in the reference -- the same position axis",
        "  used by plots 09 and 10, so these fractions line up directly with the",
        "  deamination-weighted values if you want to divide one by the other by hand.",
        "",
        "Nothing in this workbook is used to correct any plotted value elsewhere in",
        "  the script -- it is provided purely as a reference for manual normalization.",
    ])

    path = os.path.join(out_dir, "00_reference_genome_base_composition.xlsx")
    wb.save(path)
    print(f"  Saved: {path}")


print("\n" + "="*60)
print("Exporting Excel workbooks")
print("="*60)
export_genome_composition_excel(genome_base_counts, full_window_counts, FLANK_SIZE, OUTPUT_DIR)
export_site_data_excel(df_sites, FLANK_SIZE, OUTPUT_DIR)
export_plot9_excel(df_sites, FLANK_SIZE, full_window_counts, OUTPUT_DIR)
export_plot10_excel(df_sites, FLANK_SIZE, OUTPUT_DIR)
export_plot11_excel(df_sites, OUTPUT_DIR)

if GENERATE_COMPOSITION_CORRECTED:
    export_plot9b_excel(df_sites, FLANK_SIZE, full_window_counts, OUTPUT_DIR)
    export_plot10b_excel(df_sites, FLANK_SIZE, full_window_counts, OUTPUT_DIR)


# ── Summary ───────────────────────────────────────────────────────────────

def print_summary(df_sites: pd.DataFrame, dinuc_df: pd.DataFrame):
    print("\n" + "="*60)
    print("SUMMARY")
    print("="*60)
    print(f"  Covered C/G sites (coverage >= {MIN_COVERAGE})  : {len(df_sites):>10,}")
    print(f"  Total coverage across all sites          : {int(df_sites['coverage'].sum()):>10,}")
    print(f"  Total deamination observations            : {int(df_sites['n_deaminated'].sum()):>10,}")
    print(f"  Mean per-site conversion rate              : {df_sites['conv_rate'].mean():>10.4f}")
    print(f"  Median coverage                            : {df_sites['coverage'].median():>10.1f}")
    print("\n  %% C->T conversion by +1 context:")
    print(dinuc_df.to_string(index=False))
    print("="*60 + "\n")


print_summary(df_sites, dinuc_df)

print("Analysis complete!")
